name: zestypantry
version: 1.0.0+1
publish_to: none
description: A personal mart Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  fluttertoast: ^8.2.1
  cloud_firestore: ^4.7.1
  flutter_bounce: ^1.1.0
  google_fonts: ^4.0.3
  cached_network_image: ^3.2.3
  firebase_core: 2.15.0
  firebase_messaging: 14.6.5
  googleapis_auth: 1.4.1
  firebase_auth: 4.7.2
  googleapis: 11.4.0
  flutter_local_notifications: 15.1.0+1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/imgs/
    - lib/assets/
  uses-material-design: true

