name: zestypantry
version: 1.0.0+1
publish_to: none
description: A personal mart Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  fluttertoast: ^8.2.1
  cloud_firestore: ^4.7.1
  flutter_bounce: ^1.1.0
  google_fonts: ^4.0.3
  cached_network_image: ^3.2.3
  firebase_core:


  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/imgs/